### ISSUE TITLE
[AVM Module Issue]: minimum_tls_version has missing latest 1.3 version

### ISSUE THREAD

**Issue by kborowiec-mag** [Azure/terraform-azurerm-avm-res-web-site#136]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

minimum tls version cannot be set to recent 1.3

Error: expected site_config.0.minimum_tls_version to be one of ["1.1" "1.2" "1.0"], got 1.3
│
│   with module.function_appname.azurerm_linux_function_app.this[0],
│   on .terraform\modules\function_appname\main.function_app.tf line 463, in resource "azurerm_linux_function_app" "this":
│  463:     minimum_tls_version                           = var.site_config.minimum_tls_version

**Comment by donovm4** [comment]
Hello @kborowiec-mag : 

Thank you - I will look into this shortly.

**Comment by donovm4** [comment]
@kborowiec-mag : 

It appears that you will need to use [`azurerm v4.8`](https://registry.terraform.io/providers/hashicorp/azurerm/4.8.0/docs/resources/linux_function_app), but this module does not yet support `azurerm` `v4.x`.

I am preparing to release `v0.12.0` of the module, which will support `azurerm` `v4.x`, but will have a breaking change no longer supporting `azurerm` `v3.x`.

I will mark this as a feature request instead of a bug and provide an update when `v0.12.0` has been released.

**Comment by donovm4** [comment]
@kborowiec-mag : 

Please see release `0.12.0` of the module and review all release notes. This release focuses on `azurerm` `4.x` support, which will enable tls `1.3` for app service through `azurerm` `4.8`.

Consider reaching out or reopening this issue if you run into any problems.
